### ISSUE TITLE
Preventing/Reporting the creation of false data in eventDate

### ISSUE THREAD

**Issue by dbloom** [gbif/pipelines#811] opened 2022-10-25 20:26 UTC
Per the recommendation of those intrepid Helpdesk luminaries, I report an issue in eventDate that is, perhaps, an extension of, or just related to, the closed issue #389 

In a dataset I published on behalf of NAS in Colombia (https://www.gbif.org/dataset/6ce307d0-0456-4b74-b647-db0ace930b26), there are 12 records that simply contain a year (2014) for eventDate, yet, when published to GBIF, the portal "interprets" that eventDate as (e.g., https://www.gbif.org/occurrence/3413479978):

Term | Interpreted | Original | Remarks
-- | -- | -- | --
Year | 2014 | 2014 |  
Event date | 2014-01-01T00:00:00 | 2014 | Altered

I can confirm there is no additional eventDate, year, month, or day data in the source file provided to me. I can also confirm that there is no additional data in the DwC-A occurrence.txt file generated by the IPT.

This occurs for all 12 records in this dataset and it is, obviously, problematic since the interpretation/addition of a year-only date as also having occurred on January 1st is not only incorrect, it is completely imaginary and poses some serious consequences for data users.

While the truth-tellers at the Helpdesk explained why cannot be changed or fixed within the current limitations of the GBIF infrastructure, I hope that GBIF will consider the various issues with eventDate of great importance. I am concerned that these sorts of "Interpretations" of data will only increase is number and consequence as we move toward a new data model and simultaneously push for more Event Core datasets and for a greater diversity of data types.

Should it be helpful, I can provide the occurrenceIDs for all 12 records in this dataset, but I am certain VertNet has published hundreds, if not thousands, of records that contain only a year, thus all of those records are available for public use with imaginary data.

EDIT: I will add that this dataset is the subject of a data paper that should be released before the end of October and it was one of the paper's reviewers who raised this issue to my attention. We have informed them that this is not something that can be fixed at this time, but it should be noted that the publishers of data papers are also keen to keep erroneous data out of their publications.

**Comment by muttcg** [comment] 2022-10-26 09:40
Thanks @dbloom 

I will mark the issue as duplicate of https://github.com/gbif/gbif-api/issues/4 and we have many similar open issues for the same problem with dates.

Just want to remind that "pipelines" project is a part of GBIF infrastructure and there are many more projects involved in the process of getting the data from publisher and displaying on the portal page, so I'd recommend to create any GBIF data related issues at https://github.com/gbif/portal16 issue page

Pipelines as a project responsible for data interpretation works and interprets all dates and date ranges correctly, but there are many other infrastructure pieces that must be improved in order to work correctly across the GBIF infrastructure.

As an example internal data format for https://www.gbif.org/occurrence/3413479978 is:

```
"eventDate": 
{
    "gte": "2014",
    "lte": null
},

```

**Closed by muttcg** 2022-10-26 09:40 UTC
Labels: duplicate

**Comment by timrobertson100** [comment] 2022-10-26 10:25
Recording this here for future reference, since this is now linked to the epic on gbif/gbif-api#4. 

Rather than incorrectly filling the field, we might consider the implication of nullifying the `eventDate` rather than populating it incorrectly (I expect search _may_ work, and small downloads but not the SQL-based stuff). There appear to be `46,106,107` records that are affected by the issue described above.

```
SELECT count(*) FROM occurrence WHERE eventDate IS NOT NULL AND month IS NULL AND day IS NULL;
```

**Comment by dbloom** [comment] 2022-10-26 16:51
Thanks @timrobertson100 @muttcg I will track https://github.com/gbif/gbif-api/issues/4.

Also @timrobertson100 your suggestion, while not perfect within your infrastructure, would at least remove the imaginary data from the mix. I don't know what it would mean for data users - probably a new habit to look for appropriate dates in both eventDate and year, as needed.
