### ISSUE TITLE
Raise ZK timeouts

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#683] opened 2022-03-03 14:32 UTC
Often in interpretation, we see spark executor failures with stack traces similar to that below. I've observed them when the ZK nodes appear idle on Ganglia, leading me to suspect this is a long GC pause on the Spark JVM - feasible since the heap is 80GB.

I suggest the simplest option is to ensure the ZK timeout in the HBase client config is long (e.g. 10 mins) to give the executors the best chance of maintaining their ZK lease rather than failing a task.

``` 
22/03/03 08:20:57 WARN zookeeper.ZKUtil: hconnection-0x66f7109b-0x17b5d48e6750787, quorum=c5zk1.gbif.org:2181,c5zk2.gbif.org:2181,c5zk3.gbif.org:2181, baseZNode=/hbase Unable to get data of znode /hbase/table/prod_h_occurrence_lookup
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/table/prod_h_occurrence_lookup
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1151)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:354)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.getData(ZKUtil.java:623)
	at org.apache.hadoop.hbase.zookeeper.ZKTableStateClientSideReader.getTableState(ZKTableStateClientSideReader.java:185)
	at org.apache.hadoop.hbase.zookeeper.ZKTableStateClientSideReader.isDisabledTable(ZKTableStateClientSideReader.java:59)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.isTableOnlineState(ZooKeeperRegistry.java:127)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.isTableDisabled(ConnectionManager.java:1009)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.relocateRegion(ConnectionManager.java:1181)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.relocateRegion(ConnectionManager.java:1169)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getRegionLocation(ConnectionManager.java:987)
	at org.apache.hadoop.hbase.client.HRegionLocator.getRegionLocation(HRegionLocator.java:83)
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:73)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:134)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:935)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:901)
	at org.gbif.pipelines.keygen.hbase.HBaseStore.getRow(HBaseStore.java:144)
	at org.gbif.pipelines.keygen.hbase.HBaseStore.getLong(HBaseStore.java:60)
	at org.gbif.pipelines.keygen.HBaseLockingKeyService.findKey(HBaseLockingKeyService.java:303)
	at org.gbif.pipelines.keygen.HBaseLockingKeyService.findKey(HBaseLockingKeyService.java:342)
	at org.gbif.pipelines.core.interpreters.core.BasicInterpreter.lambda$interpretGbifId$0(BasicInterpreter.java:108)
	at org.gbif.pipelines.core.interpreters.Interpretation$Handler.lambda$via$0(Interpretation.java:96)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.gbif.pipelines.core.interpreters.Interpretation$Handler.via(Interpretation.java:96)
	at org.gbif.pipelines.core.interpreters.Interpretation$Condition.via(Interpretation.java:77)
	at org.gbif.pipelines.transforms.core.BasicTransform.convert(BasicTransform.java:157)
	at org.gbif.pipelines.transforms.core.BasicTransform.convert(BasicTransform.java:37)
	at org.gbif.pipelines.transforms.Transform.processElement(Transform.java:156)
	at org.gbif.pipelines.transforms.Transform.processElement(Transform.java:152)
	at org.gbif.pipelines.transforms.core.BasicTransform$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:232)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:191)
	at org.apache.beam.runners.spark.translation.DoFnRunnerWithMetrics.processElement(DoFnRunnerWithMetrics.java:65)
	at org.apache.beam.runners.spark.translation.SparkProcessContext$ProcCtxtIterator.computeNext(SparkProcessContext.java:140)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:30)
	at org.apache.beam.runners.spark.translation.SparkProcessContext$ProcCtxtIterator.computeNext(SparkProcessContext.java:138)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:187)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:381)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timrobertson100** [comment] 2022-03-03 15:45
Just spotted this on the same job, lending weight to this being GC in the spark executors themselves.

```
22/03/03 14:56:53 WARN executor.Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:821)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:850)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:850)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:850)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2005)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:850)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
22/03/03 14:56:53 WARN netty.NettyRpcEnv: Ignored failure: java.util.concurrent.TimeoutException: Cannot receive any reply from c6n4.gbif.org:35552 in 10 seconds
```

Increasing timeouts on the heartbeats within Spark may also be worth considering, although I think in this case it doesn't fail the task.

**Comment by marcos-lg** [comment] 2023-01-10 13:23
closing this since it was already implemented. Reopen it if the problem isn't solved yet.

**Closed by marcos-lg** 2023-01-10 13:23 UTC
