### ISSUE TITLE
Remove use of ala-sensitive-data-service snapshot from build

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#470] opened 2021-01-28 15:23 UTC
The `livingatlas/pipelines` module is currently referencing a SNAPSHOT version of ala-sensitive-data-service-client.

We need to have a release version of this library in nexus.ala.org.au (currently we only have snapshots) and reference in POM.

**Comment by charvolant** [comment] 2021-02-07 23:02
Requires non-snapshot versions of ala-name-matching and sds, as well before build.

**Comment by djtfmartin** [comment] 2021-02-15 11:55
Done. Thanks @charvolant

**Comment by djtfmartin** [comment] 2021-02-15 16:46
@charvolant  - Not done :)

The build for `ala-sensitive-data-service` is failing at the last stage (the upload to nexus.ala.org.au).

https://travis-ci.com/github/AtlasOfLivingAustralia/ala-sensitive-data-service

**Comment by charvolant** [comment] 2021-02-17 23:58
Partially caused by ALA nexus having a cow when there is a -test.jar artefact in releases. The maven deploy attempts to update the .pom twice and breaks the nexus release rules. Fixed in https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service/pull/7

Why it's throwing a 400 error after it's successfully uploaded the sources is still under investigation.

**Comment by vjrj** [comment] 2021-03-02 08:48
We are getting this error trying to build the dev branch
```
[ERROR] Failed to execute goal on project pipelines: Could not resolve dependencies for project au.org.ala:pipelines:jar:2.8.0-SNAPSHOT: Failed to collect dependencies at au.org.ala.sds:ala-sensitive-data-client:jar:1.1-SNAPSHOT: Failed to read artifact descriptor for au.org.ala.sds:ala-sensitive-data-client:jar:1.1-SNAPSHOT: Could not find artifact au.org.ala.sds:ala-sensitive-data-service:pom:1.1-SNAPSHOT in gbif-all (http://repository.gbif.org/content/groups/gbif) -> [Help 1]
```

I noticed that https://nexus.ala.org.au/content/repositories/snapshots/au/org/ala/sds/ala-sensitive-data-client/1.1-SNAPSHOT/maven-metadata.xml gives `404`.

Although the nexus version does not match sounds like:
https://issues.sonatype.org/browse/NEXUS-24988

With `1.0-SNAPSHOT` downloads well, but I get some compilation errors.

TIA

**Comment by djtfmartin** [comment] 2021-03-05 14:49
Ive fixed this now. 1.1 is now in the ALA nexus repository. This can be closed.

**Closed** 2021-06-25 07:41 UTC
